### concatenating 2D and 3D data

In [2]:
from __future__ import print_function
from scipy.spatial import ConvexHull
from skimage.transform import downscale_local_mean
from matplotlib.patches import Polygon
from matplotlib.collections import PatchCollection
from skimage.measure import regionprops
import numpy as np
import matplotlib.pyplot as plt
import os as os
from tqdm import tqdm as tqdm_base
def tqdm(*args, **kwargs):
    if hasattr(tqdm_base, '_instances'):
        for instance in list(tqdm_base._instances):
            tqdm_base._decr_instances(instance)
    return tqdm_base(*args, **kwargs)
from scipy.io import loadmat
import numpy as np
import pandas as pd

In [3]:


data2d = np.load('/Users/work/Documents/GitHub/mlgenomics/data_preprocessing/Wang_2018_all_2D_processed_new.npy', allow_pickle=True)

data3d = np.load('/Users/work/Documents/GitHub/mlgenomics/data_preprocessing/processed_3d_data.npy', allow_pickle=True)

In [4]:
data3d

array([[3.57142857e-02, 3.57142857e-02, 3.57142857e-02, ...,
        4.00000000e+00, 5.75000000e+02, 7.00000000e+00],
       [3.57142857e-02, 3.57142857e-02, 3.57142857e-02, ...,
        4.00000000e+00, 1.07400000e+03, 8.00000000e+00],
       [3.57142857e-02, 3.57142857e-02, 3.57142857e-02, ...,
        3.00000000e+00, 1.16400000e+03, 6.00000000e+00],
       ...,
       [1.86467788e-01, 8.98149686e-03, 5.22357045e-02, ...,
        1.56300000e+03, 1.50800000e+03, 9.40000000e+01],
       [1.06091396e-01, 7.45356727e-03, 6.71709112e-02, ...,
        1.56800000e+03, 1.39000000e+03, 9.40000000e+01],
       [5.76471586e-02, 9.75882306e-03, 3.16181893e-02, ...,
        1.64800000e+03, 1.18100000e+03, 9.40000000e+01]])

In [17]:
genes3d = pd.read_csv('/Users/work/Documents/GitHub/mlgenomics/data_as_downloaded/sequentially_encoded_Wang_et_al_2018/gene_names.csv', header = 0)

genes2d =np.load('/Users/work/Documents/GitHub/mlgenomics/data_preprocessing/2d_genes.npy', allow_pickle=True)

In [6]:
genes3d

array(['1110008F13Rik', '1110008P14Rik', '1700019D03Rik', ..., 'eRNA5',
       'mCherry', 'mTFP'], dtype=object)

In [12]:
genes2d = np.array(genes2d[['gene']]).flatten()

In [26]:
df2d = pd.DataFrame(np.concatenate(data2d))
df2d.columns =  np.append(np.array(genes2d).flatten(),(('x','y','z','dataset')))

In [40]:
df3d = pd.DataFrame(data3d)
df3d = pd.concat([ df3d,pd.DataFrame(np.repeat(33, df3d.shape[0]))], axis=1)
df3d.columns =  np.append(np.array(genes3d[['gene']]).flatten(),(('x','y','z', 'dataset')))


In [41]:
df3d

Slc17a7       Mgp      Gad1       Nov   Rasgrf2      Rorb      Cux2  \
0      0.035714  0.035714  0.035714  0.035714  0.035714  0.035714  0.035714   
1      0.035714  0.035714  0.035714  0.035714  0.035714  0.035714  0.035714   
2      0.035714  0.035714  0.035714  0.035714  0.035714  0.035714  0.035714   
3      0.035714  0.035714  0.035714  0.035714  0.035714  0.035714  0.035714   
4      0.035714  0.035714  0.035714  0.035714  0.035714  0.035714  0.035714   
5      0.035714  0.035714  0.035714  0.035714  0.035714  0.035714  0.035714   
6      0.035714  0.035714  0.035714  0.035714  0.035714  0.035714  0.035714   
7      0.002000  0.000751  0.010912  0.004835  0.002048  0.007584  0.013706   
8      0.035714  0.035714  0.035714  0.035714  0.035714  0.035714  0.035714   
9      0.035714  0.035714  0.035714  0.035714  0.035714  0.035714  0.035714   
10     0.152641  0.002815  0.002736  0.021112  0.033242  0.009691  0.019948   
11     0.124343  0.014577  0.223677  0.007252  0.008246  0.005039  0.012035   
12     0.007897  0.000794  0.000953  0.028563  0.003697  0.010381  0.001433   
13     0.198134  0.003513  0.001018  0.023209  0.015217  0.014133  0.019185   
14     0.007289  0.001732  0.001213  0.003214  0.011448  0.033629  0.006845   
15     0.008100  0.002140  0.000327  0.000327  0.007255  0.008332  0.002016   
16     0.086801  0.002643  0.011527  0.034373  0.009183  0.027133  0.004446   
17     0.092876  0.002301  0.007564  0.000730  0.010932  0.005957  0.003971   
18     0.103337  0.002478  0.003739  0.005859  0.008360  0.005461  0.000481   
19     0.017657  0.000919  0.000700  0.017866  0.008467  0.006661  0.000840   
20     0.001158  0.000650  0.008521  0.002011  0.002333  0.006964  0.004491   
21     0.001710  0.000863  0.000360  0.013335  0.006408  0.007288  0.000678   
22     0.036701  0.004450  0.059314  0.038596  0.015977  0.012322  0.024069   
23     0.004829  0.000738  0.004838  0.002439  0.009085  0.013288  0.000818   
24     0.091715  0.002439  0.000983  0.000721  0.006562  0.008127  0.002658   
25     0.005254  0.000638  0.000560  0.013801  0.006162  0.016650  0.002576   
26     0.004457  0.000262  0.000245  0.003883  0.004133  0.011561  0.004655   
27     0.011634  0.000624  0.000869  0.011282  0.005178  0.002284  0.005109   
28     0.002801  0.000558  0.000284  0.004364  0.001446  0.005293  0.009580   
29     0.057058  0.002758  0.000663  0.021690  0.015261  0.006657  0.016801   
...         ...       ...       ...       ...       ...       ...       ...   
33568  0.035714  0.035714  0.035714  0.035714  0.035714  0.035714  0.035714   
33569  0.331959  0.010100  0.009464  0.002759  0.035329  0.014174  0.077468   
33570  0.176226  0.008626  0.057256  0.044463  0.009314  0.006272  0.012501   
33571  0.276149  0.011851  0.082088  0.064514  0.033991  0.012111  0.052114   
33572  0.341649  0.014017  0.011876  0.019804  0.068143  0.013281  0.130398   
33573  0.455440  0.012711  0.022256  0.005806  0.018033  0.007302  0.031096   
33574  0.271838  0.008417  0.005803  0.002590  0.026820  0.013597  0.224523   
33575  0.324779  0.012432  0.008562  0.003322  0.035894  0.010208  0.037844   
33576  0.551854  0.013625  0.005935  0.002842  0.032433  0.006374  0.062671   
33577  0.150969  0.009682  0.112241  0.025798  0.045897  0.011561  0.143248   
33578  0.352088  0.010571  0.008475  0.007982  0.022620  0.007427  0.132114   
33579  0.096265  0.011488  0.084989  0.006486  0.045950  0.010555  0.079309   
33580  0.050660  0.014072  0.031529  0.012766  0.072505  0.009214  0.011995   
33581  0.202313  0.013339  0.161267  0.005654  0.042312  0.010070  0.132324   
33582  0.225745  0.011453  0.012890  0.036115  0.042739  0.010416  0.038669   
33583  0.145247  0.005263  0.004208  0.003054  0.020856  0.038687  0.249711   
33584  0.227200  0.007838  0.008980  0.003176  0.109361  0.011951  0.170303   
33585  0.137697  0.010507  0.100518  0.025608  0.029309  0.007870  0.056619   
33586  0.199314  0.008915  0.024490  0.004352  0.029717  0

In [44]:
allgenes = np.concatenate((genes2d, (('x','y','z', 'dataset'))))

In [48]:
 reindexed_3d =  df3d.reindex(columns = (allgenes))

In [75]:
# scale all the coordinates 

np.sum(data2d[0][:,-4:-1], axis = 0)

array([ 5498706., 10560296.,        0.])

In [58]:
threed = np.array(reindexed_3d.fillna(0))
all_data = np.concatenate((np.concatenate(data2d), threed))

In [59]:

np.savez('all_concatenated_data.npz',all_data)

In [62]:
d = np.load('all_concatenated_data.npz')['arr_0']

In [68]:
d[:,-4:-1]

array([[  19., 1951.,    0.],
       [  27., 2969.,    0.],
       [  26., 2804.,    0.],
       ...,
       [1563., 1508.,   94.],
       [1568., 1390.,   94.],
       [1648., 1181.,   94.]])

In [69]:
# divide each by the max 

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.01204819, 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])